In [1]:
import numpy as np

Создание массива, где идёт увеличение 1 по столбцу и 10 по строке

In [40]:
#вар 1
mtrx = np.array( [np.array(range(1,8))+n for n in range(0,110,10)])
mtrx

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

In [54]:
#вар 2
np.arange(1,8)+np.arange(0,101,10).reshape(11,1)

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

Выборка элементов из массива маской True - False

In [34]:
arr=np.arange(2,23)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22])

In [57]:
arr[:20][arr[:20] % 2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [63]:
arr[1:][arr[1:] % 2!=0]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [64]:
arr[:20][arr[:20] % 2==0]*arr[1:][arr[1:] % 2!=0]

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

Умножение массивов

In [68]:
np.arange(2,21,2)*np.arange(3,22,2)

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

In [80]:
x = np.arange(0,10,0.001)
arr = x * np.sin(x)
len(arr[arr>0.5])/len(arr)

0.5242

Нахождение минимального

In [116]:
arr4=np.random.randint(0,10,80).reshape(8,10)
arr4

array([[1, 7, 5, 2, 9, 1, 3, 7, 6, 7],
       [6, 8, 2, 9, 4, 2, 7, 3, 4, 7],
       [8, 6, 0, 0, 1, 2, 5, 4, 0, 3],
       [4, 7, 1, 2, 0, 8, 6, 3, 7, 2],
       [0, 5, 5, 1, 5, 5, 8, 5, 1, 9],
       [0, 1, 7, 8, 5, 5, 0, 5, 4, 7],
       [4, 3, 6, 6, 8, 8, 9, 3, 1, 2],
       [5, 3, 5, 6, 9, 1, 1, 4, 4, 8]])

In [113]:
np.where(arr4.sum(axis=1).argmin())

(array([0], dtype=int64),)

In [117]:
np.argmin(arr4, axis=1)

array([0, 2, 2, 4, 0, 0, 8, 5], dtype=int64)