In [4]:
import pandas as pd
import numpy as np
import sklearn

In [43]:
vis_data = pd.read_csv("train.csv", encoding = 'ISO-8859-1', low_memory = False)
vis_data

ticket_id                                     agency_name  \
0           22056  Buildings, Safety Engineering & Env Department   
1           27586  Buildings, Safety Engineering & Env Department   
2           22062  Buildings, Safety Engineering & Env Department   
3           22084  Buildings, Safety Engineering & Env Department   
4           22093  Buildings, Safety Engineering & Env Department   
...           ...                                             ...   
250301     325555  Buildings, Safety Engineering & Env Department   
250302     325557  Buildings, Safety Engineering & Env Department   
250303     325562  Buildings, Safety Engineering & Env Department   
250304     325559  Buildings, Safety Engineering & Env Department   
250305     325561  Buildings, Safety Engineering & Env Department   

          inspector_name                      violator_name  \
0        Sims, Martinzie  INVESTMENT INC., MIDWEST MORTGAGE   
1       Williams, Darrin           Michigan, Covenant House   
2        Sims, Martinzie                    SANDERS, DERRON   
3        Sims, Martinzie                       MOROSI, MIKE   
4        Sims, Martinzie                    NATHANIEL, NEAL   
...                  ...                                ...   
250301      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250302      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250303      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250304      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250305      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   

        violation_street_number violation_street_name  violation_zip_code  \
0                        2900.0                 TYLER                 NaN   
1                        4311.0               CENTRAL                 NaN   
2                        1449.0            LONGFELLOW                 NaN   
3                        1441.0            LONGFELLOW                 NaN   
4                        2449.0             CHURCHILL                 NaN   
...                         ...                   ...                 ...   
250301                  10701.0           SANTA MARIA                 NaN   
250302                  10701.0             MEYERS RD                 NaN   
250303                  10701.0             MEYERS RD                 NaN   
250304                  10701.0             MEYERS RD                 NaN   
250305                  10701.0             MEYERS RD                 NaN   

        mailing_address_str_number mailing_address_str_name     city  ...  \
0                              3.0                S. WICKER  CHICAGO  ...   
1                           2959.0       Martin Luther King  Detroit  ...   
2                          23658.0                 P.O. BOX  DETROIT  ...   
3                              5.0                ST. CLAIR  DETROIT  ...   
4                           7449.0                CHURCHILL  DETROIT  ...   
...                            ...                      ...      ...  ...   
250301                      1715.0                   MEYERS  DETROIT  ...   
250302                      1715.0                   MEYERS  DETROIT  ...   
250303                      1715.0                   MEYERS  DETROIT  ...   
250304                      1715.0                   MEYERS  DETROIT  ...   
250305                      1715.0                   MEYERS  DETROIT  ...   

       clean_up_cost judgment_amount payment_amount balance_due  \
0                0.0           305.0            0.0       305.0   
1                0.0           855.0          780.0        75.0   
2                0.0             0.0            0.0         0.0   
3                0.0             0.0            0.0         0.0   
4                0.0             0.0            0.0         0.0   
...              ...             ...            ...         ...   
250301           0.0             0.0            0.0         0.0   
250302           0.0             0.0

In [44]:
X = vis_data['balance_due'].values.reshape(-1, 1)
X

array([[305.],
       [ 75.],
       [  0.],
       ...,
       [  0.],
       [  0.],
       [  0.]])

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 0.13613444],
       [-0.24315767],
       [-0.36683987],
       ...,
       [-0.36683987],
       [-0.36683987],
       [-0.36683987]])

In [29]:
X_scaled.min().round(5)

-13.14733

In [46]:
new_values = []
for i in range(len(X)):
    if X[i]>0:
        new_values.append(np.sqrt(X[i]))
new_values

[array([17.4642492]),
 array([8.66025404]),
 array([17.4642492]),
 array([29.24038303]),
 array([11.83215957]),
 array([11.83215957]),
 array([29.24038303]),
 array([29.24038303]),
 array([29.24038303]),
 array([29.24038303]),
 array([3.16227766]),
 array([3.16227766]),
 array([29.24038303]),
 array([29.24038303]),
 array([29.24038303]),
 array([3.16227766]),
 array([17.4642492]),
 array([17.4642492]),
 array([17.4642492]),
 array([17.4642492]),
 array([5.]),
 array([17.4642492]),
 array([17.4642492]),
 array([5.]),
 array([2.23606798]),
 array([5.]),
 array([17.4642492]),
 array([14.14213562]),
 array([62.28964601]),
 array([17.4642492]),
 array([5.]),
 array([3.16227766]),
 array([3.16227766]),
 array([5.]),
 array([17.4642492]),
 array([5.47722558]),
 array([17.4642492]),
 array([17.4642492]),
 array([17.4642492]),
 array([15.65247584]),
 array([17.4642492]),
 array([7.58287544]),
 array([15.8113883]),
 array([4.47213595]),
 array([17.4642492]),
 array([62.28964601]),
 array([5.]),


In [47]:
medi = np.median(new_values)
ave = np.mean(new_values)
abs(medi-ave)

0.45259606090997195

In [42]:
a = [3,4,7]

SyntaxError: invalid syntax (<ipython-input-42-8995c7d287d4>, line 2)