In [2]:
import numpy as np

1) Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [3]:
a = np.arange(1, 8)
b = np.arange(0, 101, 10)
b = b.reshape(11, 1)
a+b

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

Задание 2

In [4]:
a = np.arange(2, 20, 2)
b = np.arange(3, 20, 2)
a * b

array([  6,  20,  42,  72, 110, 156, 210, 272, 342])

3) Приблизительно рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [5]:
a = np.arange(1, 11, 0.5)
a[a*np.sin(a) > 0.5]

array([1. , 1.5, 2. , 2.5, 6.5, 7. , 7.5, 8. , 8.5, 9. ])

4) Создать матрицу 8 на 10 из случайных целых (используя модуль numpy.random) чисел из дапозона от 0 до 10 и найти в ней строку, в которой сумма значений минимальна.

In [14]:
a = np.random.randint(0, 11, size=(8, 10))
print(a.sum(axis=0))
print(a.sum(axis=0).argmin())

[47 18 65 25 38 35 41 30 42 20]
1


5) Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

In [43]:
a = np.random.randint(0, 11, size=(30, 3))
b = np.random.randint(0, 11, size=(30, 3))
np.sum(a[a > b])

315

6) Написать фукнцию, которая для целых значений n и m будет возвращать матрицу размера n на m, имеющую заполнение вида. Пример для 4 на 4:

In [68]:
def get_matrix(n, m):
    n_ceil = np.ceil(n/2)
    m_ceil = np.ceil(m/2)
    a = np.arange(0, 4).reshape(2, 2)
    a = np.tile(a, (n, m))
    return a[:n, :m]

get_matrix(3, 3)

array([[0, 1, 0],
       [2, 3, 2],
       [0, 1, 0]])

7) Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [5]:
def isprime(n):
    n = abs(int(n))
    if n < 2:
        return False
    if n == 2:
        return True
    if not n & 1:
        return False
    for x in range(3, int(n**0.5)+1, 2):
        if n % x == 0:
            return False
    return True


def get_primes2(n):
    vectorized_isprime = np.vectorize(isprime)
    a = np.arange(n)
    return a[vectorized_isprime(a)]

get_primes2(100)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

In [16]:
def sieve(n):
    flags = np.ones(n, dtype=bool)
    flags[0] = flags[1] = False
    for i in range(2, n):
        if flags[i]:
            flags[i*i::i] = False
    return np.flatnonzero(flags)

sieve(100)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64)

In [17]:
%timeit sieve(1000000)

137 ms ± 311 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
