In [3]:
import numpy as np

1) Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [27]:
np.arange(0,110,10).reshape(11,1) + np.arange(1, 8)

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

In [37]:
np.arange(1, 111).reshape(11, 10)[:, :7]

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

In [28]:
def f(i, j):
    return 10 * i + j + 1

In [29]:
np.fromfunction(f, (11, 7), dtype = np.int32)

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

2) Средствами numpy рассчитать произведения четных чисел от 2 до 20
на ближайшие к ним бОльшие нечетные числа.

In [3]:
(np.arange(2,21,2))*(np.arange(3,22,2))

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

In [5]:
t2 = np.arange(2,21,2)
t2 * (t2 + 1)

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

In [7]:
t2 = np.arange(2,22)
t2[t2 % 2 == 0] * t2[t2 % 2 == 1] 

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

In [15]:
t2 = np.arange(2,22).reshape(10,2)
t2

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [17]:
t2.prod(axis=1)

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

3) Приблисзительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [57]:
np3 = np.linspace(0.0, 10.0, 10000, dtype=np.float)
len(np3[np3*np.sin(np3) > 0.5])/len(np3)

0.5241

4) Создать матрицу 8 на 10 из случайных целых (используя модуль numpy.random) чисел из дапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [80]:
m1=np.random.randint(0,11,(8,10))
print(m1)
s=m1.sum(axis=1)
print(s)
i=np.argmin(s)
print(i)
print(m1[i])

[[ 8 10  4  2  0 10  4  0  3  7]
 [ 4  6  8  0  8  5  1  6  9  3]
 [ 0  9  5  8  1  3  3  2  2  6]
 [ 1  8  3  4  3  1  5  5  0  2]
 [ 2 10  2  7  0  5  9  2  2  4]
 [ 8  9  3  4  1  6  1  2  1 10]
 [10  5  5  1  9  1  4  3  4 10]
 [ 4  5  6  5  6  6  5 10  8  6]]
[48 50 39 32 43 45 52 61]
3
[1 8 3 4 3 1 5 5 0 2]


In [4]:
np.random.randint(0,10,(8,10)).sum(1).argmin()+1

2

In [5]:
np1 = np.random.randint(0,10,(8,10))
np1

array([[0, 5, 9, 6, 8, 3, 1, 9, 7, 7],
       [2, 0, 5, 5, 0, 2, 6, 2, 9, 8],
       [7, 4, 3, 8, 9, 4, 0, 0, 4, 1],
       [2, 6, 7, 6, 5, 8, 3, 9, 2, 1],
       [0, 0, 1, 5, 9, 5, 4, 2, 3, 0],
       [1, 6, 5, 0, 9, 5, 5, 6, 8, 3],
       [1, 4, 0, 3, 9, 2, 0, 2, 8, 3],
       [9, 6, 0, 4, 0, 9, 6, 2, 2, 6]])

In [7]:
np1.sum(1)

array([55, 39, 40, 49, 29, 48, 32, 44])

In [6]:
np1.sum(1).argmin()+1

5

In [10]:
np1[np1.sum(1).argmin(), : ]

array([0, 0, 1, 5, 9, 5, 4, 2, 3, 0])

5) Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

In [57]:
m1 = np.random.randint(10, size = (30, 3))
m2 = np.random.randint(10, size = (30, 3))
np.sum(m1[m1 > m2])

307

In [58]:
m1 > m2

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False,  True],
       [False,  True,  True],
       [False, False,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False, False],
       [ True, False, False],
       [ True,  True, False],
       [ True, False, False],
       [ True, False,  True]], dtype=bool)

In [12]:
m1 = np.random.randint(0, 10, (30,3))
m2 = np.random.randint(0, 10, (30,3))
m3 = m1[m1>m2]
print(m3)
sum(m3)

[4 8 7 6 4 5 9 7 8 3 9 7 7 9 7 3 9 9 5 3 3 8 8 7 6 8 8 4 4 6 9 9 6 6 8 5 6
 8]


248

6) Написать фукнцию, которая для целых значений n и m будет возвращать матрицу размера n на m, имеющую заполнение вида.
Пример для 4 на 4:

0 1 0 1

2 3 2 3

0 1 0 1

2 3 2 3

In [59]:
n=int(input('Введите: '))
m=int(input('Введите: '))
h=np.array([[0,1],[2,3]])
h1=np.tile(h,(n//2+1,m//2+1))
h1[:n,:m]

Введите: 4
Введите: 5


array([[0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2],
       [0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2]])

In [60]:
def change(m,n):
    col_ind=np.arange(1,n,2)
    row_ind=np.arange(1,m,2)
    ar=np.zeros((m,n), dtype=int)
    ar[:,col_ind]+=1
    ar[row_ind,:]+=2
    return ar
change(4,4)

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])

In [69]:
def change2(m,n):
    s=np.tile([0,2], m//2+m%2)[0:m]
    s1=np.tile([1,3], m//2+m%2)[0:m]
    return np.tile(np.column_stack((s,s1)), n//2+n%2)[0:m,0:n]
change2(5,4)

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1]])

In [20]:
def func(n, m):
    return np.tile(np.arange(0, 4).reshape(2,2), (n//2+1, m//2+1))[:n, :m]

In [23]:
func(50, 50).shape

(52, 52)

In [29]:
def create_matrix(n: int, m: int) -> np.ndarray:
    matrix = np.zeros((n, m), dtype=np.int)
    # matrix[::2, ::2] = 0
    matrix[::2, 1::2] = 1
    matrix[1::2, ::2] = 2
    matrix[1::2, 1::2] = 3
    return matrix

In [30]:
create_matrix(5, 5)

array([[0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2],
       [0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2],
       [0, 1, 0, 1, 0]])

7) Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [34]:
def eratosfen(n):
    sieve = np.arange(0,n+1,1, dtype = np.int)
    for i in sieve:
        if i > 1:
            sieve[i+i:sieve.size:i] = 0
    return sieve
data = eratosfen(100)
print(data[data.nonzero()])

[ 1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [71]:
def eratosfen_2(n):
    arr = np.arange(2,n)
    for i in range(2, n //4):
        elon_mask = np.logical_not((arr % i == 0) & (arr !=i))
        arr = arr[elon_mask]
    print(arr)
eratosfen_2(100)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97]


In [79]:
n = 101
flags = np.ones(n, dtype=bool)

for i in range(2, n //5):
    if flags[i]:
        flags[2*i::i] = False
b = np.arange(n)
b[flags]

array([ 0,  1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47,
       53, 59, 61, 67, 71, 73, 79, 83, 89, 97])

In [35]:
def func(n):
    flags = np.ones(n, dtype=bool)
    flags[0] = flags[1] = False
    for i in range(2, n):
        if flags[i]:
            flags[i*i::i] = False
    return np.flatnonzero(flags)

func(100)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64)

In [50]:
import math

In [51]:
def isPrime(n):
    if n % 2 == 0 and n > 2 or n == 1:
        return False;
    return all(n % np.arange(3, int(math.sqrt(n)) + 1, 2))

In [53]:
a = np.arange(1, 100)
foo = np.vectorize(isPrime)
pbools = foo(a)
primes = np.extract(pbools, a)
primes

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

In [55]:
def func(n):
    flags = np.ones(n, dtype=bool)
    flags[0] = flags[1] = False
    for i in range(2, n):
        if flags[i]:
            print(f'{i} {i*np.arange(2,n//i)}')
            flags[i*np.arange(2, n//i)] = False
    return np.flatnonzero(flags)

func(100)

2 [ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52
 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
3 [ 6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78
 81 84 87 90 93 96]
5 [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
7 [14 21 28 35 42 49 56 63 70 77 84 91]
11 [22 33 44 55 66 77 88]
13 [26 39 52 65 78]
17 [34 51 68]
19 [38 57 76]
23 [46 69]
29 [58]
31 [62]
37 []
41 []
43 []
47 []
53 []
59 []
61 []
67 []
71 []
73 []
79 []
83 []
89 []
97 []
99 []


array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97, 99], dtype=int64)

8) Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [1]:
def pribliz(array, x):
    idx = np.abs(array-x).argmin()
    return array[idx]

In [6]:
mat = np.random.uniform(0, 1, 100)
pribliz(mat , 0.5), mat


(0.49951381835890252,
 array([  7.21832575e-01,   8.89875562e-01,   9.29193067e-01,
          2.63304164e-01,   4.63322950e-01,   2.52681690e-02,
          1.13399743e-01,   9.78251910e-02,   4.18233590e-01,
          1.25690075e-01,   9.47411873e-01,   5.14700156e-01,
          6.50101344e-01,   6.93444251e-01,   3.33746933e-01,
          2.49820651e-01,   7.94776832e-03,   2.77638710e-01,
          8.85488936e-01,   4.81933912e-02,   4.81281019e-01,
          5.28831800e-01,   5.63577655e-01,   6.75715481e-01,
          3.67892890e-01,   9.24446595e-01,   6.64630211e-01,
          5.57748589e-04,   2.00568902e-01,   9.04593132e-01,
          3.44705680e-01,   4.77655406e-01,   2.97623135e-01,
          4.85805706e-01,   5.14396239e-01,   5.91345647e-01,
          8.39963819e-01,   2.25745640e-01,   2.97001305e-02,
          7.08748314e-01,   3.17454681e-02,   7.28274222e-01,
          7.50297866e-01,   4.99513818e-01,   6.09872489e-01,
          4.17475839e-01,   2.47870313e-01,   6.

9) При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [7]:
matrix = np.random.random((20, 20))
i = np.arange(0, 19)
matrix[i, i + 1]

array([ 0.57283116,  0.42273149,  0.35115666,  0.46924101,  0.51512922,
        0.62608106,  0.88976968,  0.19372873,  0.33486106,  0.44012362,
        0.18352723,  0.89848521,  0.60893363,  0.01251114,  0.61158604,
        0.79603372,  0.64823309,  0.41437495,  0.80762438])

In [8]:
array = np.asarray(["Москва", "Тюмень", "Омск", "Кемерово", "Красноярск", "Краснодар", "Курс", "Саратов", "Челябинск", "Екатиринбург"])
index_array = np.random.randint(0,10,100)
print(array[index_array])

['Саратов' 'Красноярск' 'Екатиринбург' 'Омск' 'Кемерово' 'Курс' 'Москва'
 'Краснодар' 'Курс' 'Красноярск' 'Саратов' 'Краснодар' 'Челябинск'
 'Челябинск' 'Екатиринбург' 'Тюмень' 'Москва' 'Красноярск' 'Екатиринбург'
 'Краснодар' 'Омск' 'Саратов' 'Саратов' 'Красноярск' 'Курс' 'Москва'
 'Красноярск' 'Челябинск' 'Саратов' 'Краснодар' 'Москва' 'Краснодар'
 'Краснодар' 'Омск' 'Курс' 'Тюмень' 'Екатиринбург' 'Челябинск' 'Курс'
 'Кемерово' 'Курс' 'Кемерово' 'Курс' 'Москва' 'Омск' 'Саратов' 'Челябинск'
 'Екатиринбург' 'Саратов' 'Красноярск' 'Кемерово' 'Екатиринбург' 'Омск'
 'Омск' 'Краснодар' 'Москва' 'Краснодар' 'Кемерово' 'Краснодар'
 'Красноярск' 'Москва' 'Краснодар' 'Екатиринбург' 'Кемерово' 'Курс' 'Омск'
 'Краснодар' 'Омск' 'Тюмень' 'Кемерово' 'Краснодар' 'Омск' 'Кемерово'
 'Омск' 'Кемерово' 'Курс' 'Омск' 'Екатиринбург' 'Кемерово' 'Челябинск'
 'Екатиринбург' 'Курс' 'Москва' 'Краснодар' 'Тюмень' 'Саратов' 'Кемерово'
 'Екатиринбург' 'Краснодар' 'Москва' 'Курс' 'Москва' 'Омск' 'Омск' 'Курс'
 'К

10) Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

11) Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

12) Задать два двухмерных массива ar1 и ar2 размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максиум из двух значений, находящихся на аналогичной позиции в массивах ar1, ar2.

13) Задать два двухмерных массива ar1 и ar2 размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удовить все значения ar1 которые совпадают со значениями ar2, расположенными на аналогичных позициях.

14) Заданы три двухмерных массива ar1,ar2 и ar3 размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Обнулить все элемены ar1 которые больше соответствующих (находящихся в соответствующих позициях) элементов ar2 и меньше соответствующих элементов ar3.

15) Задан двухмерный массив ar1 размерности (4, 7) состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.

In [4]:
m9 = np.random.randint(0, 10, 20*20).reshape(20, 20)
m9

array([[9, 4, 2, 5, 8, 0, 9, 7, 9, 9, 1, 0, 3, 2, 6, 0, 4, 3, 7, 4],
       [8, 8, 1, 7, 8, 1, 6, 4, 7, 8, 3, 6, 7, 1, 5, 0, 3, 9, 6, 0],
       [7, 9, 8, 5, 5, 8, 4, 9, 6, 6, 2, 8, 9, 0, 5, 3, 5, 0, 8, 0],
       [8, 4, 4, 2, 4, 9, 7, 8, 4, 6, 1, 4, 7, 0, 0, 7, 5, 8, 4, 7],
       [9, 2, 4, 0, 8, 2, 7, 4, 6, 9, 1, 1, 2, 0, 1, 1, 5, 5, 5, 9],
       [0, 6, 8, 4, 5, 3, 4, 7, 8, 2, 1, 3, 8, 8, 1, 1, 6, 4, 5, 0],
       [3, 4, 1, 5, 0, 9, 3, 8, 1, 5, 8, 6, 2, 6, 8, 0, 6, 3, 0, 3],
       [8, 4, 2, 8, 3, 9, 6, 9, 1, 6, 1, 9, 2, 6, 6, 1, 3, 8, 3, 0],
       [3, 1, 9, 0, 4, 0, 9, 7, 7, 2, 6, 4, 8, 6, 1, 1, 8, 0, 4, 8],
       [6, 2, 2, 6, 5, 4, 9, 3, 6, 5, 8, 3, 4, 2, 6, 5, 5, 7, 9, 1],
       [8, 1, 7, 9, 9, 6, 0, 8, 6, 1, 5, 2, 1, 0, 0, 1, 3, 9, 0, 8],
       [6, 5, 2, 8, 1, 1, 2, 7, 2, 5, 1, 7, 1, 2, 8, 0, 4, 8, 9, 9],
       [3, 6, 5, 8, 9, 3, 2, 6, 0, 4, 5, 3, 7, 2, 5, 8, 8, 4, 8, 8],
       [0, 0, 3, 0, 2, 7, 9, 7, 9, 8, 4, 8, 2, 3, 5, 2, 6, 7, 5, 3],
       [1, 7, 9, 7, 5, 8, 8, 1, 4,

In [5]:
ind9 = np.arange(20, dtype=np.int)
ind9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
m9[ind9[:-1], ind9[1:]]

array([4, 1, 5, 4, 2, 4, 8, 1, 2, 8, 2, 1, 2, 5, 2, 3, 6, 2, 7])

10) Имеется массив из 10 названий городов. При помощи прихотливой индексации сгенерировать последовательность из 100 элементов представляющих случайный выбор из названий городов.

In [9]:
m10 = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
m10r = m10[np.random.randint(0, len(m10), 100)]
m10r

array(['d', 'f', 'a', 'b', 'b', 'a', 'c', 'j', 'f', 'a', 'e', 'i', 'a',
       'c', 'h', 'c', 'i', 'a', 'e', 'h', 'b', 'h', 'b', 'j', 'h', 'd',
       'g', 'i', 'd', 'd', 'c', 'b', 'c', 'j', 'a', 'g', 'h', 'f', 'h',
       'h', 'h', 'g', 'f', 'a', 'f', 'a', 'a', 'c', 'h', 'g', 'c', 'd',
       'b', 'f', 'b', 'b', 'f', 'd', 'i', 'b', 'g', 'i', 'h', 'f', 'f',
       'g', 'i', 'a', 'h', 'a', 'h', 'h', 'j', 'h', 'h', 'e', 'i', 'j',
       'd', 'c', 'a', 'h', 'j', 'e', 'd', 'i', 'e', 'e', 'a', 'h', 'a',
       'e', 'a', 'g', 'e', 'h', 'c', 'c', 'j', 'g'], dtype='<U1')

CSV (comma-separated values) - текстовый формат, предназначенный для представления табличных данных.

Каждая строка файла - это одна строка таблицы, разделителем (delimiter) значений колонок является символ запятой (,). Однако на практике часто используются другие разделители (в русской и других локалях запятая по умолчанию зарезервирована под десятичный разделитель, поэтому как разделитель используется точка с запятой или табуляция).

Каждая строка (строка таблицы) должна содержать одинаковое количество полей следующих в одинаковом порядке.

Значения, содержащие зарезервированные символы (двойная кавычка, запятая, точка с запятой, новая строка) обрамляются двойными кавычками ("). Если в значении встречаются кавычки — они представляются в файле в виде двух кавычек подряд.

Функция numpy.genfromtxt :

https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html

https://www.numpy.org/devdocs/user/basics.io.genfromtxt.html

Примеры наборов данных:

https://www.stats.govt.nz/large-datasets/csv-files-for-download/

Rules typical of these and other "CSV" specifications and implementations are as follows:

CSV is a delimited data format that has fields/columns separated by the comma character and records/rows terminated by newlines.

A CSV file does not require a specific character encoding, byte order, or line terminator format (some software does not support all line-end variations).

A record ends at a line terminator. However, line-terminators can be embedded as data within fields, so software must recognize quoted line-separators (see below) in order to correctly assemble an entire record from perhaps multiple lines.

All records should have the same number of fields, in the same order.

Data within fields is interpreted as a sequence of characters, not as a sequence of bits or bytes (see RFC 2046, section 4.1). For example, the numeric quantity 65535 may be represented as the 5 ASCII characters "65535" (or perhaps other forms such as "0xFFFF", "000065535.000E+00", etc.); but not as a sequence of 2 bytes intended to be treated as a single binary integer rather than as two characters (e.g. the numbers 11264-11307 have a comma as their high order byte: ord(',')*256..ord(',')*257-1). If this "plain text" convention is not followed, then the CSV file no longer contains sufficient information to interpret it correctly, the CSV file will not likely survive transmission across differing computer architectures, and will not conform to the text/csv MIME type.

Adjacent fields must be separated by a single comma. However, "CSV" formats vary greatly in this choice of separator character. In particular, in locales where the comma is used as a decimal separator, semicolon, TAB, or other characters are used instead.

2.1) Создать целочисленную невырожденную матрицу 8 на 4 (M) и целочисленный столбец 4 на 1 (a) с суммой значений больше 10 (проверить) и найти y = M * a

2.2) По значению y и M найти а

2.1) Средствами numpy рассчитать произведения четных чисел на ближайшие к ним большие нечетные числа в пределах от 2 до 20.

2.2) Приблисзительно рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

2.3) Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

3) Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

4) Написать фукнцию, которая для целых значений n и m будет возвращать матрицу размера n на m, имеющую заполнение вида.
Пример для 4 на 4:

0 1 0 1

2 3 2 3

0 1 0 1

2 3 2 3

3) Создать две матрицы 30 на 3 из случайных целых чисел из диапозона от 0 до 10 и найти все значения из первой матрицы, которые больше соответсвующих (по расположению) значений из второй матрицы. Подсчитать сумму этих значений.