In [2]:
import numpy as np

1) Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [3]:
np.arange(1, 111).reshape(11, 10)[:, 0:7]

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

2) Средствами numpy рассчитать произведения четных чисел на ближайшие к ним большие нечетные числа в пределах от 2 до 20.

In [59]:
np2 = np.arange(2, 21, 2)
np2 * (np2 + 1)

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

3) Приблисзительно рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [65]:
np3 = np.linspace(0.3, 10.0, 100000, dtype=np.float)
len(np3[np3*np.sin(np3) > 0.5]) / len(np3)

0.54034

4) Создать матрицу 8 на 10 из случайных целых (используя модуль numpy.random) чисел из дапозона от 0 до 10 и найти в ней строку, в которой сумма значений минимальна.

In [42]:
ar4 = np.random.randint(10, size=(8,10))
min(ar4.sum(axis=1))

31

5) Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

In [8]:
m1 = np.random.randint(10, size=(30,3))
m2 = np.random.randint(10, size=(30,3))
sum(sum((m1>m2)*m1))

287

6) Написать фукнцию, которая для целых значений n и m будет возвращать матрицу размера n на m, имеющую заполнение вида.
Пример для 4 на 4:

0 1 0 1

2 3 2 3

0 1 0 1

2 3 2 3

In [56]:
def func1(n, m):
    return np.tile(np.arange(0,4).reshape(2, 2), (n, m))[:n, :m]

In [58]:
func1(5, 5)

array([[0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2],
       [0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2],
       [0, 1, 0, 1, 0]])

7) Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [20]:
def sieve(n):
    flags = np.ones(n, dtype=bool)
    print(flags)
    flags[0] = flags[1] = False
    for i in range(2, n):
        if flags[i]:
            flags[i*i::i] = False
    print(flags)
    return np.flatnonzero(flags)

sieve(100)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[False False  True  True False  True False  True False False False  True
 False  True False False False  True False  True False False False  True
 False False False False False  True False  True False False False False
 False  True False False False  True False  True False False False  True
 False False False False False  True False False False False False  True
 False  True False False 

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64)

8) Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [ ]:
def Near_number(Number_elements, value):
    ar = np.random.random(Number_elements)
    dif_el = math.fabs(value - ar[0])
    el = None
    print(ar)
    for i in ar:
        if dif_el > math.fabs(value - i):
            dif_el = math.fabs(value - i)
            el = i
    return el
Near_number(10, 0.1)

9) При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [ ]:
ar = np.random.randint(10, size=(20, 20))
print(ar)
ar[range(0, 19), range(1, 20)]

10) Имеется массив из 10 названий городов. При помощи прихотливой индексации сгенерировать последовательность из 100 элементов представляющих случайный выбор из названий городов.

In [ ]:
city = ["Москва", "Волгоград", "Рязань", "Калининград", "Сочи", "Магадан", "Владивосток", "Казань", "Муром", "Владивосток"]
final_list = []

ar = np.random.randint(0, 10, size=100)[np.random.randint(0, 10, size=100)]

for i in ar:
    final_list.append(city[i])
    
len(final_list)